### ISSUE TITLE
Uncaught TypeError: Cannot read property 'error_messages' of undefined

### ISSUE THREAD

**Issue by shantell2005** [QuizandSurveyMaster/quiz_master_next#1261]
Title: Javascript error detected by QSM Plugin
Message: Uncaught TypeError: Cannot read property 'error_messages' of undefined
Filename: https://content.personalfinancelab.com/wp-content/cache/minify/b2f64.js:21:166
Stack: TypeError: Cannot read property 'error_messages' of undefined
    at qmnValidation (https://content.personalfinancelab.com/wp-content/cache/minify/b2f64.js:21:166)
    at qmnFormSubmit (https://content.personalfinancelab.com/wp-content/cache/minify/b2f64.js:32:185)
    at HTMLFormElement.<anonymous> (https://content.personalfinancelab.com/wp-content/cache/minify/b2f64.js:68:237)
    at HTMLFormElement.dispatch (https://content.personalfinancelab.com/wp-content/cache/minify/4015f.js:318:476)
    at HTMLFormElement.elemData.handle (https://content.personalfinancelab.com/wp-content/cache/minify/4015f.js:304:166)
Page url: https://content.personalfinancelab.com/quiz/bubba-chapter-7/?v=c4782f5abe5c
Refferer: https://content.personalfinancelab.com/investing101/chapter-6/?v=c4782f5abe5c
User-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 Edg/88.0.705.74
Screen size: 1366×768×24
Screen orientation: landscape-primary
Cookie enabled: true

**Comment by pranav-et** [comment]
Hi @shantell2005 ,

To ensure the proper functionality of QSM quizzes, it is important to adjust the settings of your caching plugin accordingly. Specifically, you should:

**Exclude QSM Quizzes from Caching**: Configure your caching plugin to bypass caching for all pages containing QSM quizzes. This prevents the plugin from serving outdated or static versions of quiz pages, ensuring that quizzes load dynamically and function as expected.

**Exclude JavaScript (JS) Files from Minification**: Many caching plugins offer JS minification to improve performance. However, minifying QSM-related JS files can lead to compatibility issues or errors in the quiz functionality. To avoid this, exclude QSM’s JavaScript files from the minification process in your caching plugin’s settings.

By applying these exclusions, you ensure seamless quiz operations without disruptions caused by caching or JS minification conflicts.

Thanks
