### ISSUE TITLE
Question Type - Head To Head

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#19]
User wants a question type where a quiz taker can choose between 2 images/videos/media.

**Comment by OC2PS** [comment]
There's always the radio button questions. However, sometimes, all you want to do is compare 2 entities. To make the experience richer, one would like to use head-to-head comparisons. Sample http://imgur.com/NPWXCBI

See how in this image, quiz taker can click on the pictures to choose between the options? How instead of showing radio buttons below the images "buttons" are shown, clicking on which has the same effect as clicking on the images?

**Comment by OC2PS** [comment]
Sad to see this go stale. Would like to see some progress on this. There are lots of use cases.
