### ISSUE TITLE
Some words in responses causes strange behavior

### ISSUE THREAD

**Issue by cedrick-f** [QuizandSurveyMaster/quiz_master_next#1959]
Hi 

## Site Info
WordPress Version: 5.9.4
QSM Version: 8.0.3
Browser: Firefox

## General description
When I put the word 'syntaxe' among responses of a multiple choice question, and if "questions per pages" is enabled, there are no Start button (no question selected ?)

## Expected behavior
All expected questions should be used.

## Actual behavior
Only 'syntaxe' is causing the issue. It works fine with 'syntax' and 'syntaxes'

## Steps to reproduce the behavior
Create a new quiz with '1 question per page' option enabled
Create a new question (multiple choices) and add some responses.
Use the word 'syntaxe' in one of them

Thanks by advance

**Comment by cedrick-f** [comment]
Hi

After careful consideration, I think the problem comes from the glossary of my site, witch contains this word, 'syntaxe'. Somewhere, QSM seams to replace 'syntaxe' by the tooltip associated.
I m using the WordPress.org Glossary plugin and if I disable it, everything works fine.

I would appreciate if you could make QSM compatible with WordPress.org Glossary plugin.
Thanks

**Comment by etvarun** [comment]
@cedrick-f 

We tried replicating this issue as per your description. However we are not able to replicate this issue on our end even after trying several combinations of settings.

Kindly try replicating this on latest version of QSM and WordPress once. If the issue is still there, please provide us a staging url where we can see this issue and troubleshoot further.

We will try our best to resolve this issue from our side. 

Regards,
Varun
