### ISSUE TITLE
CRITICAL - Response doesn't save

### ISSUE THREAD

**Issue by Aldmors** [QuizandSurveyMaster/quiz_master_next#2066]
## Site Info
WordPress Version: 6.1.1
QSM Version: 
Browser: 7.3.7

## General description
The response doesn't save to DB and plugin doesn't report this information in frontend for users and in admin panel

the response body:
![image](https://user-images.githubusercontent.com/48130167/211867136-f7d10a18-9aeb-4c16-b59e-a251b43dfd96.png)

**Comment by Aldmors** [comment]
We organize a nationwide competition and so far it has been carried out using your application (that's why a lot of feedbacks were returned) but the issue that the participants 'responses were not saved is critical and is a significant problem for us, because the first stage of the competition "disappeared" :)

**Comment by Aldmors** [comment]
Site Information
Site URL: https://glospokolenia.pl
Home URL: https://glospokolenia.pl
Multisite: No
WordPress Information
Version: 6.1.1
Language: en_US
Permalink Structure: /%year%/%monthnum%/%postname%/
Active Theme: Blocksy 1.8.65Parent Theme: Blocksy 1.8.65
Debug Mode: Disabled
Memory Limit: 40M
Plugins Information
Must Use
WordPress automation by >Aplikacje_cyberFolks:
Active
Blocksy Companion: 1.8.65
CookieYes | GDPR Cookie Consent: 3.0.8
Edit Flow: 0.9.7
GS Logo Slider Lite: 3.4.0
Hoo Docx Document File Importer: 1.0.2
Members: 3.2.2
Nested Pages: 3.2.3
podcast player: 6.2.0
PublishPress Checklists: 2.7.3
QSM Theme - Companion: 1.0.0
Quiz And Survey Master: 8.0.8
Reading Time WP: 2.0.12
Simple-JWT-Login: 3.5.0
Slim SEO: 3.16.5
Ultimate Member: 2.5.3
Inactive
JobBoardWP: 1.2.2
One Click Accessibility: 2.1.0
WP-Optimize - Clean, Compress, Cache: 3.2.10
WP Rollback: 1.7.2
Server Information
PHP : 8.0.25
MySQL : 10.5.17
Webserver : LiteSpeed
QSM Information
Initial Version : 7.3.7
Current Version : 8.0.8
Total Quizzes : 2
Total Active Quizzes : 1
Total Questions : 325
Total Active Questions : 325
Total Results : 0
Total Active Results : 0
QSM Recent Logs
No recent logs

**Comment by etvarun** [comment]
Hi @Aldmors,

Thank you for bringing this to our attention and apologies for a late response.

We're sorry to hear that you're experiencing difficulties with our plugin, and we want to help you get to the bottom of this.

It will be very helpful if you can provide us any or all of the following logs:
1. WordPress debug logs
2. DB error logs
3. Server error logs

We need to know where the failure might have occurred in order to troubleshoot further.

We are also planning to add a feature soon which will create an incident log inside the plugin if a quiz submission fails due to any reason.

We apologize for any inconvenience this may have caused and appreciate your patience while we work together to resolve this issue.

Best regards,
Varun
