### ISSUE TITLE
Submissions not registered

### ISSUE THREAD

**Issue by hctn** [QuizandSurveyMaster/quiz_master_next#2426]
## Site Info
WordPress Version: 6.4.2
QSM Version: 8.0.8
Browser: All

## General description
I created a quiz a week ago, in which just under a hundred people took part, spread over a week. At the end of their participation, 43 entries were recorded in the plugin's "Results" tab. More than twenty people raised the following concern: they had taken part, received the automatic e-mail confirming their participation, yet we could find no trace of their participation in the results. The theory of unintentional manual deletion is highly improbable, particularly as the unrecorded submissions took place on very different dates, separated by submissions that were themselves recorded. Do you have any idea where this is coming from?

## Expected behavior
The survey submission should be systematically recorded in the "Results" tab and the automatic confirmation e-mail sent.

## Actual behavior
The survey submission is not recorded in the "Results" tab, but the automatic confirmation e-mail is sent.

## Steps to reproduce the behavior
When submitting the quiz, some submissions are not taken into account

**Comment by zubairraeen** [comment]
Hi, 

Could you please share the quiz URL and provide additional details, such as whether the issue is still occurring? Have you set up SMTP for email sending? If possible, could you also share the server configuration details (e.g., PHP version, max upload size, etc.)? You can find these details under **Settings > Tools** in your WordPress dashboard. 

Thank you!
