### ISSUE TITLE
Saving a session to resume later

### ISSUE THREAD

**Issue by gamekid88** [QuizandSurveyMaster/quiz_master_next#250]
Admins want to allow for the ability on longer quizzes and surveys to save and come back later to finish.

**Comment by fpcorso** [comment]
Another request for this feature from the forums: https://wordpress.org/support/topic/save-question-when-user-leave-field/

**Comment by sriordan9** [comment]
Another request for this feature has been made

**Comment by fpcorso** [comment]
Hey @bpanatta!

I will definitely accept any help with this one. Between this one and #210 (Saving answers locally), there have been many requests for some way to have the user come back to the quiz to finish.

Unfortunately, there are many different caveats due to the nature of a quiz and results software. That said, it looks like your proposed requirements would handle most of these. 

One of the biggest issues is all the other systems, addons, and custom solutions that are currently just querying the results table to pull all results. If we add another column or two to designate status, I fear partial results will be reported as complete for any current or previous systems.

The other caveat would be if the admin does not currently require quiz takers to have an account. Would this feature require admins to create accounts for quiz takers in order to use this feature? I wonder if, instead of using a session ID, we just have the one column for status (i.e. complete/partial). If partial, we could match the user's ID if logged in or email if not logged in, as long as the admin is asking for email in that quiz.

These two challenges are the reason I haven't found a way to create this system yet.

The next question would be: What different settings would need to be built? You listed the one to enable to option which is a definite must but would we need one to switch between automatic/manual saving? Or, a way to allow both? If there is automatic, do we need a way to disclose the form is saving automatically or should that be up to the quiz creator?

For the automatic saving, I don't know if attaching that to changing quiz page event will work in all cases. There are many quiz creators who list out 100+ questions all on one page with the submit at the bottom. I wonder if we could have the automatic saving be every set amount of time (i.e. every x seconds) or attached to answering every set number of questions (i.e. save after every x questions).

I am just about finished with 6.2.0 (hopefully today!) and will send out the beta. Once I am wrapped up with that, I can circle back to this and brainstorm a little more on it.

**Comment by bpanatta** [comment]
Thanks for the fast reply and for shedding more light into the problem!

About the status column, there are 3 other ways I can think of:
1. Creating a table only for partials;
2. Using an existing column to include the partials data (like negating the total score).
3. Using the `quiz_results` column to check if the results are partial or not.

The first two seems to affect readability, and doesn't fit in a well crafted plugin like this.
As for the third, it would have a slow performance depending on the check, but should not affect other functionalities and addons.

> The other caveat would be if the admin does not currently require quiz takers to have an account. Would this feature require admins to create accounts for quiz takers in order to use this feature?
Your proposed solution seems to work perfectly, maybe we could place a check in the contact options in order for the admin to select which field should be used to compare, but for a start just the email would do the job.

As for saving options, we could have two:
1. Enable save button (which would enable manual saving);
2. Automatic save options: no save, save every page change, save every X seconds, save every X questions, save every page change and every X seconds, save every page change and every X questions.

What do you think of it?
