### ISSUE TITLE
HIPAA Compliant

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#322]
A few users have asked for this plugin to be HIPAA compliant. I need to do a lot more research into the subject so I can see what I'll have to change to ensure that it is compliant.

**Comment by danieliser** [comment]
Did they mention anything in particular? You may have lucked out here as I have brought several doctors offices into com pliancy from top to bottom. I need to hear more about what they asked to see how they feel it applies here. But I know the regulations well enough to guide you to a solution.

**Comment by fpcorso** [comment]
No, it wasn't anything specific that was mentioned. The most recent just asked if it was HIPAA compliant and I said I would look into it.

**Comment by fpcorso** [comment]
I know she wanted to use the surveys to ask for personal information to be sent to doctors.

**Comment by danieliser** [comment]
Can you reach out to them? Depends on their usage

**Comment by danieliser** [comment]
Are they a medical office already? Are these existing patients that have already signed medical record consent forms?

**Comment by fpcorso** [comment]
What would I need to ask them? Just for more information on exactly how they are using the surveys? They pointed to a tier at Survey Monkey that says "HIPAA-COMPLIANT FEATURES
Safeguard protected health information with HIPAA-compliant features and a Business Associate Agreement."

**Comment by danieliser** [comment]
The business associate agreement is something that any contractor / service that can potentially come in contact with patient data must sign. For instance if I go into a dr's office to fix PCs and can potentially have access to patient info I must sign one. If the AC repair guy comes in and is near a computer in the back or by the records room, then he also has to sign.

Likely since that is a hosted service ( Survey Monkey ), the data is stored on there end requiring them to be associates of the practice, as well as making sure that the servers are secure to hipaa standards.

Since the form and data are on their own site as long as their site is already compliant you would be fine.. To them that simply means that all users have appropriate access and that only people allowed to see the data can access it. But really the compliance in this case is on their end, unlike survey monkey.

Let me know if I need to clarify anything.
