### ISSUE TITLE
Two Part Quiz

### ISSUE THREAD

**Issue by JenniferWenger** [QuizandSurveyMaster/quiz_master_next#336]
My client would like to have their users complete the Quiz, get a score and then be able to add a comment about their score. 

I am thinking that a 2 part quiz would allow me to have them take the first part, receive a score and then immediately comment on that score. Is this possible, and could the comments be linked to the main part of the quiz? Also, we will be adding the plugin to show users their past scores. My client also wants them to be able to see all of their comments. 

If this is something we can purchase, I would be happy to discuss it. Please contact me as soon as possible.

Thank you!

Jennifer

**Comment by fpcorso** [comment]
Greetings @JenniferWenger 

Thank you for choosing to use this plugin! This plugin doesn't currently have a way to show the results of the two different quizzes or parts together which would be an issue here since the client would not be able to show the scores with their comments. It would show results for the score and then results for the comments as two separate results. I'll definitely keep this in mind and keep it on my to-do list but I cannot currently offer a time-frame for when this will be implemented.
