### ISSUE TITLE
Point totals may be incorrect when using decimals

### ISSUE THREAD

**Issue by peshmerge** [QuizandSurveyMaster/quiz_master_next#364]
I have a problem with the points, grading system. I have made a simple test quize to show that the grading system is incorrect. 
I have three questions: 
the first question has Correct/good answers:  first one worth 1 point and the second has 0.5 point
but when I give an answer which has 0.5 point, it shows me 1 points 
![1](https://cloud.githubusercontent.com/assets/531558/12496118/f598ba4e-c093-11e5-8d4d-b4b8fc562715.png)

Here is the questions with given answers in: 
![2](https://cloud.githubusercontent.com/assets/531558/12496243/ca011ea2-c094-11e5-96fc-e72e396f5f60.png)

and here what I have got as result:
![3](https://cloud.githubusercontent.com/assets/531558/12496248/d79f516e-c094-11e5-9061-98bac919f7bb.png)

Here the questions with their options: 
Question1:
![4](https://cloud.githubusercontent.com/assets/531558/12496260/03e2cc9c-c095-11e5-8419-bed06d1fe36e.png)

Question2:
![5](https://cloud.githubusercontent.com/assets/531558/12496272/182a7e70-c095-11e5-8dce-df798c421120.png)

Question3:
![6](https://cloud.githubusercontent.com/assets/531558/12496292/345756e0-c095-11e5-95eb-b813c1b96a0c.png)

PS: I have made this quiz to show what the problem is. Many times it shows incorrect scores. It seems there is something wrong with the way the points are calculated. 

Thanks :)

**Comment by peshmerge** [comment]
Really annoying and crap support. I have bought a pro version to get support also. Holy shit is this service. I posted this question 11 days ago.

**Comment by fpcorso** [comment]
Greetings @peshmerge 

Thank you for choosing to use this plugin! First, as the Help page in the plugin, the WordPress support forums, the support page on the website, and the Readme in the repo all say, GitHub is not the place for support. To receive support, please use the appropriate channels listed in many places throughout the plugin, the website, and the support forums. The average response time in the appropriate channels is 18 hours. As this repo is only one of dozens that I maintain, I only look through these issues when I am in working in this repo which I haven't done since my last release 2 weeks ago. I am now coming in now to work on the next update and am going through the issues.

As for your GitHub issue:

Your pictures show the score is correct. You answered "incorrect" which is worth 0.5 points, "2" which is worth 0 points, and "niks" which is worth 0.5 points. When totaled, your score is then 1 point. Can you provide a few pictures where the scoring is incorrect? Alternatively, can you provide a link to a quiz and tell me what answers to choose to see the score being incorrect?
