### ISSUE TITLE
Capcha question should stay last even if quiz is set to random

### ISSUE THREAD

**Issue by OctavianBRT** [QuizandSurveyMaster/quiz_master_next#376]
Hi there,

First of all I want to say that your plugin is one of the best around. I am setting it up for use on my website but I noticed a few thing that you might want to add to your plugin:
1. Iti is great that you implemented a capcha question but it would be great it it would stay as a last question even if the quiz is set to random questions. I use random questions because this way a user can retake the quiz later without it feeling too familiar but this way the user encounters the capcha in the middle of the quiz.
2. You should add a simple facebook share button on the results page because not every website has an facebook app and the user should be able to share at least a message with a link to the quiz page even if I dont have a facebook app.

Thank you for the plugin!

**Comment by fpcorso** [comment]
Hey @OctavianBRT. Thank you for choosing to use this plugin! The captcha is definitely something I want to change and even have an issue created #328 and even a bug #311 with the current version. I hope to remove the question type captcha and replace it with an option in the settings that will add one to the end of the quiz rather than within the randomize questions.

As for the Facebook button, I will look into the API to see if I can find a way to remove the App ID limitation.
