### ISSUE TITLE
Display total votes an answer receives 

### ISSUE THREAD

**Issue by dukeran** [QuizandSurveyMaster/quiz_master_next#458]
User requested to be able to have a survey with a single question and 4 multiple choice answers. For results, user would like to be able to show visitors the percentage (%) of the total votes each answer has received.

**Comment by EnzoCostantini** [comment]
If this is a tool to make a survey, this is the minimal feature!!!

**Comment by fpcorso** [comment]
Hey @EnzoCostantini! Thanks for your feedback. 

This has been an in-depth conversation among the team. I see surveys as more of data collection to be reviewed internally and polls as more of data collection to be displayed externally. Since there are so many poll plugins and products, one being Poll Daddy owned by the team behind WordPress, I found it better to focus this product towards surveys.

That said, we have been getting more and more requests for more poll-like features such as this one, so we are discussing the possibility of broadening our views on what surveys are.

I would greatly appreciate your thoughts on this @EnzoCostantini.

**Comment by vikasprogrammer** [comment]
We have implemented a new shortcode for results page - %POLL_RESULTS_X%, where X is the question ID. You can now find out the question id by editing a question. 

Fixed in v6.3.1 https://github.com/QuizandSurveyMaster/quiz_master_next/releases/tag/6.3.1
