### ISSUE TITLE
Can't add video anymore

### ISSUE THREAD

**Issue by johanna52** [QuizandSurveyMaster/quiz_master_next#546]
After the 5.0 update it is impossible to add videos to a quiz anymore.
When you click on save with a question, the video isn't added.
Also when you change a question with a video already in it, the video isn't displayed anymore.
Hopefully this can be solved.

Johanna

**Comment by fpcorso** [comment]
I've spent a bit of time trying to figure this out. First, the shortcode function to run the [embed] code doesn't work outside of the post loop. ([WordPress Trac Issue](https://core.trac.wordpress.org/ticket/23431)). Some of the workarounds are possible but could cause significant slowdowns depending on how the other plugins on the site are using the filters since this has to run for every single question. Some sites have 100+ questions in a quiz.

On the opposite end, the plugin is also having trouble with dropping in iframes. With the latest round of security additions, we are using kses to prevent a variety of elements from being used. Apparently, the default kses for posts disallows iframes such as YouTube embed. Looking into alternatives here as well.

**Comment by ELepolt** [comment]
Hey @fpcorso, any update on this at all?

**Comment by sriordan9** [comment]
Work around found...please follow the steps below:
​
- ​In the question editor click the "Add Media" button
- Under the header "Create Video Playlist" click the "Upload Files" tab
- Upload the video (the max file size will be displayed under the "select file" button)
- To the bottom right you will have a dropdown menu, choose the "embed media player" option
 -The video will now be in the question

**Comment by zubairraeen** [comment]
Hello,  
I have tested this issue with the latest version of QSM, and it is now resolved and functioning correctly. Therefore, I am closing this task.  

Thank you!
