### ISSUE TITLE
css and js files don't load if WP Rocket plugin is active for the site

### ISSUE THREAD

**Issue by vlood** [QuizandSurveyMaster/quiz_master_next#594]
## General description
WP Rocket creates a cache file for each script and style of a plugin that is being enqueued. Urls of styles and scripts that contain '..' don't load properly, as their url becomes 'http://mysite.com/wp-content/cache/busting/1/wp-content-plugins-quiz-master-next-php-..-templates-qmn_primary-5.1.1.css'. 

## Expected behavior
When url of the enqueued script/style does not contain "..", WP Rocket caches them properly and they are loaded by visitors browsers.

## Possible solution
As a quick-fix I defined another constant in mlw-quizmaster2.php:
`define( 'QSM_PLUGIN_BASEDIR', plugin_basename( __DIR__ ) );`
Then scripts and styles are enqueued like this:
`wp_enqueue_style( 'qmn_quiz_style', plugins_url() . QSM_PLUGIN_BASEDIR . '/css/qmn_quiz.css' );`

If you find my solution as acceptable, I could send a PR.

**Comment by fpcorso** [comment]
Hey @vlood 

Thanks for using QSM! It has been quite a while since I wrote the code for the template CSS but I feel like there was a reason I used the '..' instead of a global constant but cannot think of what it could have been. If you want to create a PR, I will test it out. If everything works well, I'll go ahead and accept it for the next version.
