### ISSUE TITLE
CM Tooltip Glossary v3.6.4 by CreativeMindsSolutions

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#691]
## General description
This plugin conflict prevents the quiz submit button from working. No other known information on the conflict at this time.

**Comment by fpcorso** [comment]
The repo for this plugin can be found here: https://wordpress.org/plugins/enhanced-tooltipglossary/

**Comment by fpcorso** [comment]
I tested the plugins together on a local site and there is definitely a conflict but I am unsure as to why.

Since we could have multiple quizzes/surveys on the same page and we load the content during page load at different parts of the page (depending on where the shortcode is placed), we currently echo out the data inside of <script> elements on the page. We have out qmn_quiz_data JavaScript object that contains all of the data.

Before the quiz is created, we add a:
`if (window.qmn_quiz_data === undefined) {
	window.qmn_quiz_data = new Object();
}` as shown here: https://github.com/fpcorso/quiz_master_next/blob/master/php/classes/class-qmn-quiz-manager.php#L118

This is to prevent an `Cannot set property '1' of undefined` error.

However, when CM Tooltips is activated, this part of our code is removed for some reason which causes the error to appear. The data does not get set so the initialization functions do not get called.

I looked at their code but haven't seen why this is happening.
