### ISSUE TITLE
Script error.

### ISSUE THREAD

**Issue by MUKJHARE** [QuizandSurveyMaster/quiz_master_next#909]
Title: Javascript error detected by QSM Plugin
Message: Script error.
Filename: :0:0
Stack: 
Page url: https://sujeka.com/?quiz=practice-set-gk
Refferer: https://sujeka.com/wp-admin/admin.php?page=quiz-master-next%2Fmlw_quizmaster2.php
User-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
Screen size: 1280×1024×24
Screen orientation: landscape-primary
Cookie enabled: true

**Comment by etvarun** [comment]
Hi @MUKJHARE 

The above notification was generated because there was a JS error on your website. This was detected and reported by QSM plugin since it may prevent the plugin to work properly on this website.

I checked the given URL and noticed that there is no issue from QSM side. 

Please use the latest version of QSM to prevent this kind of notifications in future.

Regards,
Varun
